Additional edits/fixes for Healpix
FRBs/astropath pull request #14
Opened 2022-01-25 15:23 UTC by profxj

As titled

2022-02-01 16:29 UTC, tarraneh requested changes
Few minor changes

2022-02-02 22:13 UTC, profxj commented on astropath/healpix.py
> +
they can have any units.  But they must be an angle object.

2022-02-02 22:14 UTC, profxj commented on astropath/healpix.py
> +    Returns:
done

2022-02-02 22:15 UTC, profxj commented on astropath/tests/test_healpix.py
> +    assert len(hp_tbl) == 4959
added

2022-02-08 14:25 UTC, tarraneh approved these changes
Looks good

2022-02-12 14:49 UTC, merged